import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header.jsx'
import Nav from '../components/Nav.jsx'
import Results from '../components/Results.jsx'
import requests from '../utils/requests.js'

export default function Home({ results }) {
  return (
    <div>
      <Head>
        <title>Hulu Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header : Hero Icons */}
      <Header />

      {/* Nav Bar */}
      <Nav />

      {/* Results : Serverside Rendering : Lazy Loading*/}
      <Results results={results}/>
    </div>
  );
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;

  const request = await fetch(
    `https://api.themoviedb.org/3${requests[genre]?.url || requests.fetchTrending.url}`
  )
  .then((res) => res.json());
  return {
    props: {
      results: request.results,
    }
  }
  // https://api.themoviedb.org/3/movie/550?api_key=16bd3ce985b5c8360595cedd76cc09d4
}
